export const FETCHED_DRIVERS = 'FETCHED_DRIVERS';
export const FETCHED_DRIVERS_START = 'FETCHED_DRIVERS_START';
export const FETCHED_DRIVERS_SUCCESS = 'FETCHED_DRIVERS_SUCCESS';
export const FETCHED_DRIVERS_ERROR = 'FETCHED_DRIVERS_ERROR';
export const UPDATE_DRIVER = 'UPDATE_DRIVER';

export const FETCHED_ORDERS = 'FETCHED_ORDERS';
export const FETCHED_ORDERS_START = 'FETCHED_ORDERS_START';
export const FETCHED_ORDERS_SUCCESS = 'FETCHED_ORDERS_SUCCESS';
export const FETCHED_ORDERS_ERROR = 'FETCHED_ORDERS_ERROR';
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_TO_LIST = 'ADD_ORDER_TO_LIST';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const ADD_UPDATED_ORDER_TO_LIST = 'ADD_UPDATED_ORDER_TO_LIST';
export const CHANGE_SELECTED_LIST = 'CHANGE_SELECTED_LIST';
export const CLEAR_SELECTED_LIST = 'CLEAR_SELECTED_LIST';

export const FETCHED_ADDITIONAL_ORDERS = 'FETCHED_ADDITIONAL_ORDERS';
export const FETCHED_ADDITIONAL_ORDERS_START = 'FETCHED_ADDITIONAL_ORDERS_START';
export const FETCHED_ADDITIONAL_ORDERS_SUCCESS = 'FETCHED_ADDITIONAL_ORDERS_SUCCESS';
export const FETCHED_ADDITIONAL_ORDERS_ERROR = 'FETCHED_ADDITIONAL_ORDERS_ERROR';

export const SET_PARAMS = 'SET_PARAMS';
export const SET_ORDERS_REQUEST_PARAMS = 'SET_ORDERS_REQUEST_PARAMS';

export const FETCHED_FILTER_ORDERS = 'FETCHED_FILTER_ORDERS';
export const FETCHED_FILTER_ORDERS_START = 'FETCHED_FILTER_ORDERS_START';
export const FETCHED_FILTER_ORDERS_SUCCESS = 'FETCHED_FILTER_ORDERS_SUCCESS';
export const FETCHED_FILTER_ORDERS_ERROR = 'FETCHED_FILTER_ORDERS_ERROR';

export const FETCHED_ORDERS_BY_DRIVER = 'FETCHED_ORDERS_BY_DRIVER';
export const FETCHED_ORDERS_BY_DRIVER_START = 'FETCHED_ORDERS_BY_DRIVER_START';
export const FETCHED_ORDERS_BY_DRIVER_SUCCESS = 'FETCHED_ORDERS_BY_DRIVER_SUCCESS';
export const FETCHED_ORDERS_BY_DRIVER_ERROR = 'FETCHED_ORDERS_BY_DRIVER_ERROR';

export const SET_DRIVER_ORDERS = 'SET_DRIVER_ORDERS';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const FETCH_STATUSES = 'FETCH_STATUSES';
export const FETCHED_STATUSES_START = 'FETCHED_STATUSES_START';
export const FETCHED_STATUSES_SUCCESS = 'FETCHED_STATUSES_SUCCESS';
export const FETCHED_STATUSES_ERROR = 'FETCHED_STATUSES_ERROR';

export const SET_STATUS = 'SET_STATUS';
export const SET_STATUSES_START = 'SET_STATUSES_START';
export const SET_STATUSES_SUCCESS = 'SET_STATUSES_SUCCESS';
export const SET_STATUSES_ERROR = 'SET_STATUSES_ERROR';

export const ASSIGN_REQUEST = 'ASSIGN_REQUEST';
export const ASSIGN_ORDERS_START = 'ASSIGN_ORDERS_START';
export const ASSIGN_ORDERS_SUCCESS = 'ASSIGN_ORDERS_SUCCESS';
export const ASSIGN_ORDERS_ERROR = 'ASSIGN_ORDERS_ERROR';

export const CANCEL_STATUS_CONFIRM = 'CANCEL_STATUS_CONFIRM';
export const CANCEL_STATUS_CONFIRM_START = 'CANCEL_STATUS_CONFIRM_START';
export const CANCEL_STATUS_CONFIRM_SUCCESS = 'CANCEL_STATUS_CONFIRM_SUCCESS';
export const CANCEL_STATUS_CONFIRM_ERROR = 'CANCEL_STATUS_CONFIRM_ERROR';

export const CANCEL_REASON = 'CANCEL_REASON';
export const FETCHED_CANCEL_REASON_START = 'FETCHED_CANCEL_REASON_START';
export const FETCHED_CANCEL_REASON_SUCCESS = 'FETCHED_CANCEL_REASON_SUCCESS';
export const FETCHED_CANCEL_REASON_ERROR = 'FETCHED_CANCEL_REASON_ERROR';

export const SHOW_DRIVER_INFO = 'SHOW_DRIVER_INFO';

export const FETCHED_CHAT_USERS = 'FETCHED_CHAT_USERS';
export const FETCHED_CHAT_USERS_START = 'FETCHED_CHAT_USERS_START';
export const FETCHED_CHAT_USERS_SUCCESS = 'FETCHED_CHAT_USERS_SUCCESS';
export const FETCHED_CHAT_USERS_ERROR = 'FETCHED_CHAT_USERS_ERROR';
export const SEARCH_CHAT_USERS = 'SEARCH_CHAT_USERS';
export const FILTER_CHAT_USERS = 'FILTER_CHAT_USERS';
export const FETCHED_MESSAGES_START = 'FETCHED_MESSAGES_START';
export const FETCHED_MESSAGES_SUCCESS = 'FETCHED_MESSAGES_SUCCESS';
export const FETCHED_MESSAGES_ERROR = 'FETCHED_MESSAGES_ERROR';
export const FETCHED_MESSAGES = 'FETCHED_MESSAGES';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const ADD_MESSAGES_ASYNC = 'ADD_MESSAGES_ASYNC';

export const CHANGE_ACTIVE_FIELD = 'CHANGE_ACTIVE_FIELD';
export const SET_SEARCH_PICKUP_ADDRESS = 'SET_SEARCH_PICKUP_ADDRESS';
export const SET_SEARCH_DROPOFF_ADDRESS = 'SET_SEARCH_DROPOFF_ADDRESS';



